# Generated by Django 2.1.8 on 2020-05-31 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='essay',
            name='comment',
            field=models.ManyToManyField(blank=True, to='roadmapData.Comment'),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='comment',
            field=models.ManyToManyField(blank=True, to='roadmapData.Comment'),
        ),
    ]
