# Generated by Django 3.0.5 on 2020-04-19 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roadmapData', '0002_auto_20200417_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_references',
            field=models.ManyToManyField(blank=True, related_name='_article_article_references_+', to='roadmapData.Article'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='readrecord',
            name='article',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='roadmapData.Article'),
        ),
        migrations.AlterField(
            model_name='readrecord',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='articles',
            field=models.ManyToManyField(blank=True, to='roadmapData.Article'),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='essays',
            field=models.ManyToManyField(blank=True, to='roadmapData.Essay'),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='road_maps',
            field=models.ManyToManyField(blank=True, related_name='_roadmap_road_maps_+', to='roadmapData.RoadMap'),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
