# Generated by Django 3.0.5 on 2020-04-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapData', '0003_auto_20200419_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
