# Generated by Django 2.1.8 on 2020-04-29 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapData', '0003_auto_20200430_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadMapShareId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(max_length=64)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmapData.RoadMap')),
            ],
        ),
    ]
