# Generated by Django 2.1.8 on 2020-05-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapData', '0004_roadmapshareid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.TextField(blank=True, default=''),
        ),
    ]
