# Generated by Django 2.1.8 on 2020-06-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapData', '0005_auto_20200601_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essay',
            name='read_state',
        ),
        migrations.AddField(
            model_name='essay',
            name='state',
            field=models.CharField(blank=True, choices=[('U', 'unfinished'), ('I', 'writing'), ('F', 'finished')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='read_state',
            field=models.CharField(blank=True, choices=[('I', 'reading'), ('U', 'unread'), ('F', 'read')], default='U', max_length=1),
        ),
    ]
