# Generated by Django 2.1.8 on 2020-06-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapData', '0006_auto_20200601_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='read_state',
            field=models.CharField(choices=[('U', 'unread'), ('I', 'reading'), ('F', 'read')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='essay',
            name='state',
            field=models.CharField(choices=[('U', 'unfinished'), ('I', 'writing'), ('F', 'finished')], default='U', max_length=1),
        ),
    ]
