# Generated by Django 2.1.8 on 2020-06-02 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapData', '0007_auto_20200601_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayShareId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(max_length=64)),
                ('essay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmapData.Essay')),
            ],
        ),
    ]
