# Generated by Django 2.1.8 on 2020-05-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapData', '0007_auto_20200504_0914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EssayTags',
            new_name='ArticleTag',
        ),
        migrations.RenameModel(
            old_name='ArticleTags',
            new_name='EssayTag',
        ),
        migrations.RenameModel(
            old_name='RoadMapTags',
            new_name='RoadMapTag',
        ),
        migrations.RemoveField(
            model_name='articletag',
            name='essays',
        ),
        migrations.RemoveField(
            model_name='essaytag',
            name='articles',
        ),
        migrations.AddField(
            model_name='articletag',
            name='articles',
            field=models.ManyToManyField(blank=True, to='roadmapData.Article'),
        ),
        migrations.AddField(
            model_name='essaytag',
            name='essays',
            field=models.ManyToManyField(blank=True, to='roadmapData.Essay'),
        ),
    ]
