# Generated by Django 2.1.8 on 2020-06-02 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapData', '0008_essayshareid'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_essay', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_roadmap', to=settings.AUTH_USER_MODEL),
        ),
    ]
