# Generated by Django 2.1.8 on 2020-05-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapData', '0009_auto_20200504_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
