# Generated by Django 2.1.8 on 2020-06-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapData', '0009_auto_20200602_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pages',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
