# Generated by Django 2.1.8 on 2020-06-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapData', '0010_auto_20200603_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abbrtitle',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
