# Generated by Django 2.1.8 on 2020-05-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapData', '0010_auto_20200520_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bibtext',
            field=models.TextField(blank=True, default=''),
        ),
    ]
