# Generated by Django 2.1.8 on 2020-05-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapData', '0012_auto_20200525_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interests',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='Interests',
        ),
    ]
