# Generated by Django 2.1.8 on 2020-05-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapData', '0012_auto_20200525_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='interests',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='Interests',
        ),
        migrations.AddField(
            model_name='newpaper',
            name='term',
            field=models.ManyToManyField(blank=True, to='roadmapData.Term'),
        ),
    ]
