# Generated by Django 2.1.8 on 2020-05-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapData', '0013_auto_20200527_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='newpaper',
            name='term',
            field=models.ManyToManyField(blank=True, to='roadmapData.Term'),
        ),
    ]
