# Generated by Django 2.1.8 on 2020-05-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapData', '0013_auto_20200527_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='abstract',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='essay',
            name='author',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='essay',
            name='state',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
