# Generated by Django 2.1.8 on 2020-05-27 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapData', '0014_auto_20200527_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='essays',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='roadmaps',
        ),
    ]
