# Generated by Django 2.1.8 on 2020-05-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapData', '0016_roadmap_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, to='roadmapData.Tag'),
        ),
        migrations.AddField(
            model_name='essay',
            name='tag',
            field=models.ManyToManyField(blank=True, to='roadmapData.Tag'),
        ),
    ]
