# Generated by Django 3.0.5 on 2020-04-17 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('author', models.CharField(blank=True, default='', max_length=200)),
                ('journal', models.CharField(blank=True, default='', max_length=200)),
                ('volume', models.IntegerField(blank=True, default=0)),
                ('pages', models.IntegerField(blank=True, default=0)),
                ('years', models.IntegerField(blank=True, default=0)),
                ('url', models.URLField(default='')),
                ('article_references', models.ManyToManyField(null=True, related_name='_article_article_references_+', to='roadmapData.Article')),
                ('user', models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoadMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('articles', models.ManyToManyField(null=True, to='roadmapData.Article')),
                ('essays', models.ManyToManyField(null=True, to='roadmapData.Essay')),
                ('road_maps', models.ManyToManyField(null=True, related_name='_roadmap_road_maps_+', to='roadmapData.RoadMap')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
