# Generated by Django 3.0.5 on 2020-04-22 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapData', '0004_auto_20200421_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_references',
        ),
        migrations.AddField(
            model_name='article',
            name='article_references',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadmapData.Article'),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='articles',
            field=models.ManyToManyField(blank=True, null=True, to='roadmapData.Article'),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='essays',
            field=models.ManyToManyField(blank=True, null=True, to='roadmapData.Essay'),
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='road_maps',
        ),
        migrations.AddField(
            model_name='roadmap',
            name='road_maps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadmapData.RoadMap'),
        ),
    ]
