# Generated by Django 3.0.5 on 2020-04-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapData', '0006_auto_20200422_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_references',
            field=models.ManyToManyField(blank=True, to='roadmapData.Article'),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='articles',
            field=models.ManyToManyField(blank=True, to='roadmapData.Article'),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='essays',
            field=models.ManyToManyField(blank=True, to='roadmapData.Essay'),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='road_maps',
            field=models.ManyToManyField(blank=True, to='roadmapData.RoadMap'),
        ),
    ]
